---
title: |
  | Supporting Information for:
  | Funnel web spiders are a menace
subtitle: "\\quad"
date: "`r format(Sys.time(), '%d %B %Y')`"
author: |
  | \normalsize Jeffrey O. Hanson*^1^
  |     \newline
  | \small ^1^School of Biological Sciences, The University of Queensland, Saint Lucia, QLD, Australia
  | \small *email jeffrey.hanson@uqconnect.edu.au
fontsize: 11pt
documentclass: article
subparagraph: true
geometry: margin=1in
bibliography: references.bib
csl: reference-style.csl
output:
  rmarkdown::pdf_document:
    fig_caption: yes
    keep_tex: yes
    includes:
      in_header: preamble.tex
---

```{r, include = FALSE}
knitr::opts_knit$set(root.dir = normalizePath("../.."))
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, dev = "png", dev.args = list(type = "cairo"), dpi = 500, fig.align = "center")
```

\newcommand{\oldtabcolsep}{\tabcolsep}
\renewcommand{\thefigure}{S\arabic{figure}}
\renewcommand{\thetable}{S\arabic{table}}

```{r, include = FALSE}
# restore session
session::restore.session("data/final/results.rda")

# load helper functions
source("code/R/functions/helpers.R")
```

```{r, include=FALSE}
## save supporting information files
setwd('../..')

# Table S1
write.table(hole.DF, 'article/Table_S1.csv', sep=',', row.names=FALSE)

# Table S2
names(visit.DF) <- c("Transect_Number", "Date", "Number_Holes_Observed", "Start_Time", "End_Time", "Search_Time")
visit.DF$Number_Holes_Estimated_From_Model <- jags.fit$BUGSoutput$summary[curr_rows,'mean'][as.numeric(visit.DF$Transect_Number)]
visit.DF %>% select(Transect_Number:Number_Holes_Observed, Number_Holes_Estimated_From_Model, Start_Time:Search_Time)
write.table(visit.DF, 'article/Table_S2.csv', sep=',', row.names=FALSE)
```
